// This file is auto generated by xlsx
import data from './Example.json';

export namespace xlsx {
    export interface ExampleObj {
        a: number;
        b: string;
    }
    export interface ExampleObjList {
        a: number;
        b: string;
    }
    export interface Example {
        id: number;
        str: string;
        bool: boolean;
        num: number;
        nlist: number[];
        slist: string[];
        obj: ExampleObj;
        objList: ExampleObjList[];
        onlyClient: string;
    }
} // namespace xlsx

export default data as xlsx.Example[];