// This file is auto generated by xlsx
import data from './Example.json';

export interface ExcelExampleObj {
    a: number;
    b: string;
    }
export interface ExcelExampleObjList {
    a: number;
    b: string;
    }
export interface ExcelExample {
    id: number;
    str: string;
    bool: boolean;
    num: number;
    nlist: number[];
    slist: string[];
    obj: ExcelExampleObj;
    objList: ExcelExampleObjList[];
    onlyClient: string;
    }

export default data as ExcelExample[];